version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres-db
    environment:
      POSTGRES_USER: myuser #dummy value
      POSTGRES_PASSWORD: mypassword #dummy value
      POSTGRES_DB: mydb #dummy value
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
